### ISSUE TITLE
Incremental SAGA Blogpost

### ISSUE THREAD

**Issue by mrocklin** [scisprints/2018_05_sklearn_skimage_dask#23]
@fabianp any interest in working together to write up something short?  I have a skeleton draft up here: http://matthewrocklin.com/blog/work/2018/07/08/incremental-saga .

**Comment by mrocklin** [comment]
Also, my most recent implementation of this (about a month ago) is here: http://nbviewer.jupyter.org/urls/gist.github.com/mrocklin/3f64e82dd5aae56fedd0655cb05bf3ef/raw/fe82aaa67981f18851a6fd1a7f4b79bfacbf9cdc/SAGA-dask.ipynb

**Comment by fabianp** [comment]
Hi Matthew,

Sure! However I'm at a conference this week. Will be back on Sunday and will have some time next week to work on it.

Is there perhaps a .md or .html file with the blog post that I can directly edit?

**Comment by mrocklin** [comment]
Yes, there is a markdown file here:
https://github.com/mrocklin/blog/blob/gh-pages/_posts/work/2018-07-08-incremental-saga.md

**Comment by fabianp** [comment]
got it thanks! I'm finally back to SF. I'll work on the TODOs and send a 
pull request by the end of the week.

Cheers

**Comment by mrocklin** [comment]
This is out: http://matthewrocklin.com/blog/work/2018/08/07/incremental-saga

**Comment by fabianp** [comment]
This is great, thanks for writing it!

**Comment by mrocklin** [comment]
Thanks to you as well.  Closing!
